namespace MySkodaSharp.Enums
{
    public enum OperationName
    {
        APPLY_BACKUP,
        LOCK,
        SET_AIR_CONDITIONING_AT_UNLOCK,
        SET_AIR_CONDITIONING_SEATS_HEATING,
        SET_AIR_CONDITIONING_TARGET_TEMPERATURE,
        SET_AIR_CONDITIONING_TIMERS,
        SET_AIR_CONDITIONING_WITHOUT_EXTERNAL_POWER,
        SET_CLIMATE_PLANS,
        START_ACTIVE_VENTILATION,
        START_AIR_CONDITIONING,
        START_AUXILIARY_HEATING,
        START_CHARGING,
        START_FLASH,
        START_HONK,
        START_WINDOW_HEATING,
        START_STOP_CHARGING,
        STOP_ACTIVE_VENTILATION,
        STOP_AIR_CONDITIONING,
        STOP_AUXILIARY_HEATING,
        STOP_CHARGING,
        STOP_WINDOW_HEATING,
        UNLOCK,
        UPDATE_AUTO_UNLOCK_PLUG,
        UPDATE_BATTERY_SUPPORT,
        UPDATE_CARE_MODE,
        UPDATE_CHARGE_LIMIT,
        UPDATE_CHARGE_MODE,
        UPDATE_CHARGING_CURRENT,
        UPDATE_CHARGING_PROFILES,
        UPDATE_DEPARTURE_TIMERS,
        UPDATE_MINIMAL_SOC,
        UPDATE_TARGET_TEMPERATURE,
        WAKEUP,
        WINDOWS_HEATING
    }

    public enum OperationStatus
    {
        IN_PROGRESS,
        COMPLETED_SUCCESS,
        COMPLETED_WARNING,
        ERROR
    }
}
