name: .NET

on:
  push:
    branches: [ "master", "develop" ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      nuget: MySkodaSharp/MySkodaSharp.csproj

    steps:

    # Checkout
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'true'
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build project
    - name: Build project
      run: dotnet build --configuration Release --no-restore

    # Pack NuGet
    - name: Pack the NuGet package
      run: dotnet pack ${{github.workspace}}/${{env.nuget}} --configuration Release --no-restore --output ./output

    # Upload artifact
    - name: Upload NuGet package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: ./output/*.nupkg

    # Publish nuget
    - name: Publish NuGet to GitHub Packages
      if: startsWith(github.ref, 'refs/tags/')
      run: dotnet nuget push ./output/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"